version: '3.9'

# this just example... not tested
# use it if you want deploy to swarm

services:
  app:
    image: async-news-filter
    mem_limit: 500M
    build:
      context: ./
      dockerfile: docker/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          cpus: '1.00'
          memory: 700M
        reservations:
          cpus: '0.25'
          memory: 500M
    command: python server.py
    ports:
      - 8080
    restart: always

  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - 0.0.0.0:8080:80
    deploy:
      replicas: 1
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app

# supports only for swarm
configs:
  nginx_conf:
    file: ./docker/nginx.conf
