version: '2.4'

services:
  app:
    image: async-news-filter
    mem_limit: 500M
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: python server.py
    volumes:
      - ./:/app
    ports:
      - 8080
    restart: always

  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
